---
title: "Homework 3"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(patchwork)

knitr::opts_chunk$set(
  fig.width = 12,
  fig.height = 10, 
  out.width = "90%"
)
theme_set(theme_bw() + theme(legend.position = "bottom"))
```

## Problem 1
load and clean the BRFSS data:
```{r clean_BRFSS}
library(p8105.datasets)
data(brfss_smart2010)

brfss_data = 
  brfss_smart2010 %>% 
  janitor::clean_names() %>% 
  rename(state = locationabbr, location = locationdesc) %>% 
  filter(topic == "Overall Health") %>% 
  mutate(response = factor(response, levels = 
                             c("Excellent", "Very good", "Good", "Fair", "Poor")))
```
Answer the following questions:

a.In 2002, which states were observed at 7 locations?
```{r count_location}
brfss_data %>% 
  group_by(year, state) %>%
  summarize(n_location = n_distinct(location)) %>% 
  filter(year == 2002, n_location == 7)
```
From the result, we can see in 2002, CT, FL and NC were observed at 7 locations.
